import type { Note, RoadmapPhase, CouncilExpert, WolfitwayProduct } from "@/types";

export const WOLFITWAY_PRODUCTS: WolfitwayProduct[] = [
  {
    id: "sync",
    name: "Wolfitway Sovereign Cloud Sync",
    domain: "sync.wolfitway.com",
    icon: "⚡",
    desc: "End-to-end encrypted multi-device synchronization relay. Zero metadata retention.",
    placeholder: "wfw_sync_live_key...",
  },
  {
    id: "ai",
    name: "Wolfitway AI Reasoning Network",
    domain: "ai.wolfitway.com",
    icon: "🧠",
    desc: "Decentralized neural reasoning relay for automated milestone extraction and roadmap synthesis.",
    placeholder: "wfw_ai_live_token...",
  },
  {
    id: "roadmap",
    name: "Wolfitway Public Roadmap Publisher",
    domain: "roadmap.wolfitway.com",
    icon: "🗺️",
    desc: "One-click static roadmap publishing engine for creator communities and investors.",
    placeholder: "wfw_pub_live_token...",
  },
  {
    id: "identity",
    name: "Wolfitway Sovereign Identity & PGP Keyring",
    domain: "id.wolfitway.com",
    icon: "🛡️",
    desc: "Hardware-bound cryptographic proof of authorship and deterministic release signing.",
    placeholder: "wfw_id_live_key...",
  },
];

export const SOVEREIGN_EXPERTS: CouncilExpert[] = [
  {
    role: "Software IP & Commercial Licensing Counsel",
    handle: "@legal-counsel",
    avatar: "⚖️",
    mandate: "Governs dual-use licensing terms (Free Solo vs Commercial Solo vs Team Pack) ensuring rock-solid copyright and zero enterprise exposure.",
    status: "Active Council",
    discipline: "Licensing & Legal",
  },
  {
    role: "Enterprise Multi-Tenant & Team Systems Architect",
    handle: "@enterprise-arch",
    avatar: "🏢",
    mandate: "Architects zero-cloud team synchronization, Git-backed mesh synchronization, multi-seat nodes, and shared credential vaults.",
    status: "Active Council",
    discipline: "Team & Enterprise Architecture",
  },
  {
    role: "SaaS & Desktop Commercialization Strategist",
    handle: "@monetization-lead",
    avatar: "💰",
    mandate: "Structures commercial solo ($49) and team mesh ($19/seat/mo) monetization funnels with frictionless zero-friction upgrades.",
    status: "Active Council",
    discipline: "Monetization & Growth",
  },
  {
    role: "Chief Product & Funnel Architect",
    handle: "@product-strategist",
    avatar: "🏛️",
    mandate: "Translates high-leverage capture notes into structured creator funnels (TOFU → MOFU → Core Engine → Revenue).",
    status: "Active Council",
    discipline: "Product Strategy",
  },
  {
    role: "Principal Systems & Cryptography Engineer",
    handle: "@systems-crypto",
    avatar: "🔐",
    mandate: "Guarantees 100% local-first ownership, AES-256-GCM hardware key encryption, and zero-telemetry offline execution.",
    status: "Active Council",
    discipline: "Systems & Security",
  },
  {
    role: "Lead UX/UI & Motion Engineering Guardian",
    handle: "@design-guardian",
    avatar: "🎨",
    mandate: "Preserves the cyber-obsidian design language, emerald luminescence, responsive cards, and zero design drift.",
    status: "Active Council",
    discipline: "Design Systems",
  },
  {
    role: "AI & Semantic Context Specialist",
    handle: "@ai-context-engineer",
    avatar: "🧠",
    mandate: "Provides transparent multi-model attribution, smart decision rationale tracking, and research exploration synthesis.",
    status: "Active Council",
    discipline: "AI & Reasoning",
  },
  {
    role: "User Flow & Cognitive Ergonomics Architect",
    handle: "@user-flow-architect",
    avatar: "🌊",
    mandate: "Eliminates cognitive friction via full-focus writing modes, universal drag-and-drop reordering, and tactile feedback.",
    status: "Active Council",
    discipline: "Ergonomics & Flow",
  },
  {
    role: "CRO & Funnel Velocity Strategist",
    handle: "@cro-strategist",
    avatar: "📈",
    mandate: "Optimizes action triggers (<3s Quick Capture, ⌘K spotlight, direct-on-canvas editing) for creator velocity.",
    status: "Active Council",
    discipline: "Growth & CRO",
  },
  {
    role: "Accessibility (a11y) & Inclusive Interaction Specialist",
    handle: "@a11y-specialist",
    avatar: "♿",
    mandate: "Enforces WCAG 2.1 AAA high-contrast standards, full keyboard navigation traps, and visible glowing emerald focus rings.",
    status: "Active Council",
    discipline: "Accessibility",
  },
];

export const INITIAL_ROADMAP: RoadmapPhase[] = [
  {
    id: "phase-1",
    number: 1,
    title: "Calmer Presence",
    subtitle: "Daily calm systems",
    status: "In Progress",
    description: "Build the foundation for calmer, more intentional daily presence. Move from reaction to response. Create space. Choose with clarity.",
    focus: "Daily calm systems",
    outcome: "More space, less noise",
    collapsed: false,
    practices: [
      { id: "p1-1", text: "Morning grounding", completed: true },
      { id: "p1-2", text: "Digital minimal defaults", completed: true },
      { id: "p1-3", text: "Pause & realign moments", completed: true },
    ],
  },
  {
    id: "phase-2",
    number: 2,
    title: "Inner Compass",
    subtitle: "Decision clarity",
    status: "Up Next",
    description: "Strengthen self-trust and clarity to navigate decisions with ease.",
    focus: "Core values & intuition",
    outcome: "Aligned execution & ease",
    collapsed: false,
    practices: [
      { id: "p2-1", text: "Values alignment checklist", completed: true },
      { id: "p2-2", text: "Intuition journaling ritual", completed: false },
      { id: "p2-3", text: "Weekly clarity debrief", completed: false },
    ],
  },
  {
    id: "phase-3",
    number: 3,
    title: "Human-Mode OS",
    subtitle: "Focus & energy systems",
    status: "Live",
    description: "Lightweight system for focus, energy, and meaningful defaults.",
    focus: "Deep work & rhythm",
    outcome: "Sustained momentum",
    collapsed: false,
    practices: [
      { id: "p3-1", text: "Deep work time-blocking engine", completed: true },
      { id: "p3-2", text: "Energy baseline tracking", completed: true },
      { id: "p3-3", text: "Evening recovery buffer", completed: true },
    ],
  },
  {
    id: "phase-4",
    number: 4,
    title: "Deeper Connection",
    subtitle: "Meaningful presence",
    status: "Planned",
    description: "Cultivate relationships and presence that recharge and inspire.",
    focus: "Community & resonance",
    outcome: "Deep fulfillment",
    collapsed: false,
    practices: [
      { id: "p4-1", text: "Weekly intentional check-in", completed: false },
      { id: "p4-2", text: "Peer feedback sanctuary", completed: false },
    ],
  },
];


export const INITIAL_NOTES: Note[] = [
  {
    id: 1,
    created_at: "2026-09-27T10:00:00Z",
    title: "Q3 Infrastructure Overhaul",
    body: "Goal Rebuild deployment pipeline for scale and resilience. Focus on zero-downtime, automated rollbacks, and better observability. Context - High deployment latency causing feedback friction - Inconsistent staging vs production environments - Need automated rollback triggers on Prometheus p99 anomalies Open questions - Do we migrate fully to Nix-based container builds? - Can we achieve sub-60-second end-to-end integration tests?",
    tags: ["infra", "pipeline"],
    kind: "milestone",
    status: "ideation",
    funnel_stage: "product",
    remind_at: "2026-10-01",
    events: [
      {
        id: "ev-1",
        title: "Idea captured",
        time: "10m ago",
        author: "You",
        desc: "Initial concept and problem framing.",
        tags: ["capture", "planning"],
      },
      {
        id: "ev-2",
        title: "Research started",
        time: "8m ago",
        author: "You",
        desc: "Reviewed current pipeline bottlenecks.",
        tags: ["research", "profiling"],
      },
      {
        id: "ev-3",
        title: "Stakeholder input",
        time: "5m ago",
        author: "Platform Team",
        desc: "Collected feedback from Platform team.",
        tags: ["feedback", "platform"],
      },
    ],
    ai_explorations: [
      {
        id: "ai-1",
        title: "Zero-downtime rollback & canary strategies",
        date: "10m ago",
        model: "Multi-Model Debate Consensus",
        url: "https://github.com/wolfnoteapp/architecture/discussions/42",
        rationale: "Automated canary analysis with instant traffic shift and automated rollback upon elevated error rates.",
        decision_outcome: "Consensus Reached: Adopt Progressive Delivery with Envoy ingress routing, backed by automated rollback upon telemetry error threshold exceeding 0.05%.",
        transcript: "Multi-turn debate between Claude 3.7 and Gemini 2.5 on blue-green vs canary deployments with automated telemetry gates.",
        tags: ["canary", "automation", "k8s", "consensus"],
        status: "consensus_reached",
        key_takeaways: [
          "Zero service disruption guaranteed during rolling cluster upgrades",
          "Automated instant rollback within 250ms of anomaly detection",
        ],
        tradeoffs: [
          {
            aspect: "Canary Routing vs Blue-Green",
            pro: "50% less idle infrastructure cost during staging",
            con: "Requires granular layer-7 traffic shifting headers",
          },
        ],
        debate_turns: [
          {
            id: "turn_1",
            speaker: "Claude 3.7 Sonnet",
            avatar: "🧠",
            stance: "pro",
            argument: "Canary routing allows testing real client telemetry with 1% traffic before committing a full production rollout.",
            timestamp: "12m ago",
          },
          {
            id: "turn_2",
            speaker: "DeepSeek R1 Reasoning",
            avatar: "🔮",
            stance: "con",
            argument: "Database schema migrations must remain backwards-compatible for N-1 versions to avoid replication desync.",
            timestamp: "10m ago",
          },
          {
            id: "turn_3",
            speaker: "Gemini 2.5 Pro",
            avatar: "✨",
            stance: "synthesis",
            argument: "Consensus: Implement expand-and-contract database migrations coupled with automated Envoy ingress traffic shifting.",
            timestamp: "6m ago",
          },
        ],
      },
      {
        id: "ai-2",
        title: "Observability & Tracing Architecture",
        date: "8m ago",
        model: "Gemini 2.5 Pro",
        rationale: "OpenTelemetry protocol collector for distributed tracing and Prometheus alert thresholds.",
        transcript: "Synthesized metrics telemetry schema. Configured Grafana dashboard alerts for latency anomalies.",
        tags: ["opentelemetry", "monitoring", "grafana"],
        status: "consensus_reached",
        key_takeaways: [
          "Sub-millisecond trace overhead across IPC boundaries",
        ],
      },
    ],
    bookmarks: [
      {
        id: "bm-1",
        url: "https://vitejs.dev",
        title: "Vite Next Generation Tooling",
        domain: "vitejs.dev",
        date: "Sep 27",
        description: "Lightning fast HMR & optimized production bundling for sovereign browser applications.",
        note: "Lightning fast HMR & optimized production bundling",
        tags: ["tooling", "bundler"],
        expert_reviews: [
          {
            expert: "Elena Rostova",
            avatar: "🛡️",
            role: "Security Architect",
            score: 9.8,
            verdict: "Approved",
            comment: "Clean build pipeline with no telemetry injected into production bundles.",
          },
          {
            expert: "Alex Mercer",
            avatar: "⚡",
            role: "Systems Lead",
            score: 9.9,
            verdict: "Approved",
            comment: "Rollup core engine produces ultra-compact ES module chunks under 75KB.",
          },
        ],
      },
      {
        id: "bm-2",
        url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/",
        title: "Kubernetes Zero-Downtime Deployment Strategy",
        domain: "kubernetes.io",
        date: "Sep 27",
        description: "Rolling update parameters, surge allocation limits, and health probes.",
        note: "Rolling update parameters & surge allocation limits",
        tags: ["k8s", "devops"],
        expert_reviews: [
          {
            expert: "Elena Rostova",
            avatar: "🛡️",
            role: "Security Architect",
            score: 9.4,
            verdict: "Approved",
            comment: "Enforce network policies and RBAC security contexts.",
          },
        ],
      },
      {
        id: "bm-3",
        url: "https://sqlite.org",
        title: "SQLite Zero-Configuration SQL Database Engine",
        domain: "sqlite.org",
        date: "Sep 27",
        description: "Self-contained, serverless, transactional SQL database engine for sovereign storage.",
        note: "Distributed tracing protocol standards",
        tags: ["database", "sqlite", "offline-first"],
        expert_reviews: [
          {
            expert: "Elena Rostova",
            avatar: "🛡️",
            role: "Security Architect",
            score: 10.0,
            verdict: "Approved",
            comment: "Gold standard for sovereign local-first privacy. Zero network socket exposure.",
          },
          {
            expert: "Dan & Council",
            avatar: "🐺",
            role: "Sovereign Pack Lead",
            score: 10.0,
            verdict: "Approved",
            comment: "The sovereign baseline for our multi-decade data preservation architecture.",
          },
        ],
      },
    ],
    mood_gallery: [
      {
        id: "mood-1",
        url: "/assets/mood-sample-1.jpg",
        caption: "Cyber-Obsidian Architecture",
        tags: ["architecture", "cyber", "dark-ui"],
        created_at: "Sep 27",
      },
      {
        id: "mood-2",
        url: "/assets/mood-sample-2.jpg",
        caption: "Emerald Neon Luminescence",
        tags: ["emerald", "neon", "palette"],
        created_at: "Sep 27",
      },
      {
        id: "mood-3",
        url: "/assets/mood-sample-3.jpg",
        caption: "Zero-Knowledge Hardware Vault",
        tags: ["crypto", "vault", "security"],
        created_at: "Sep 27",
      },
    ],
  },
  {
    id: 2,
    created_at: "2026-09-27T08:00:00Z",
    title: "AI Assistant Context Engine",
    body: "Improve long-term memory and context relevance across sovereign project timelines using local vector embeddings.",
    tags: ["ai", "memory"],
    kind: "idea",
    status: "research",
    funnel_stage: "lead_magnet",
    remind_at: "2026-10-05",
    events: [
      {
        id: "ev-ai-1",
        title: "Vector Store Research",
        time: "5h ago",
        author: "AI Assistant",
        desc: "Benchmarked SQLite VSS vs in-memory FAISS indices.",
        tags: ["embeddings", "vector-db"],
      },
    ],
    ai_explorations: [
      {
        id: "ai-3",
        title: "Hierarchical Context Compression",
        date: "5h ago",
        model: "Gemini 2.5",
        rationale: "Multi-level summarization keeps 100k+ token sessions fast and cost-effective.",
        transcript: "Benchmarked compression ratio at 82% token reduction with 99.4% factual recall.",
        tags: ["context", "compression", "rag"],
      },
    ],
    bookmarks: [
      {
        id: "bm-ai-1",
        url: "https://github.com/chroma-core/chroma",
        title: "Chroma Open-Source Vector Database",
        domain: "github.com",
        date: "Sep 27",
        note: "Embedded vector database with Python and TypeScript bindings",
        tags: ["vector-db", "open-source"],
      },
    ],
    mood_gallery: [
      {
        id: "mood-ai-1",
        url: "/assets/mood-sample-2.jpg",
        caption: "Neural Network Topography",
        tags: ["ai", "topology", "emerald"],
        created_at: "Sep 27",
      },
    ],
  },
  {
    id: 3,
    created_at: "2026-09-27T07:00:00Z",
    title: "Mobile Offline Sync",
    body: "Enable reliable offline-first workflows across mobile devices without third-party server lock-in.",
    tags: ["mobile", "offline"],
    kind: "idea",
    status: "ideation",
    funnel_stage: "product",
    remind_at: "2026-10-15",
    events: [
      {
        id: "ev-mob-1",
        title: "CRDT Protocol Drafted",
        time: "2h ago",
        author: "Systems Crypto",
        desc: "Evaluated Yjs state-based CRDTs for mobile delta sync.",
        tags: ["crdt", "sync"],
      },
    ],
    bookmarks: [
      {
        id: "bm-mob-1",
        url: "https://yjs.dev",
        title: "Yjs Shared Editing Framework",
        domain: "yjs.dev",
        date: "Sep 27",
        note: "Peer-to-peer real-time conflict-free collaborative data types",
        tags: ["crdt", "offline-first"],
      },
    ],
    mood_gallery: [
      {
        id: "mood-mob-1",
        url: "/assets/mood-sample-3.jpg",
        caption: "Local-First P2P Mesh Topology",
        tags: ["mesh", "p2p", "security"],
        created_at: "Sep 27",
      },
    ],
  },
  {
    id: 4,
    created_at: "2026-09-27T05:00:00Z",
    title: "Design System v2",
    body: "Unify components and improve developer experience with sovereign obsidian dark mode tokens.",
    tags: ["design", "ui"],
    kind: "post",
    status: "design",
    funnel_stage: "awareness",
    remind_at: null,
    events: [
      {
        id: "ev-ds-1",
        title: "Palette Finalized",
        time: "6h ago",
        author: "Design Guardian",
        desc: "Harmonized deep cyber-obsidian with emerald neon accents.",
        tags: ["tokens", "styling"],
      },
    ],
    bookmarks: [
      {
        id: "bm-ds-1",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl",
        title: "Modern HSL Color Palettes",
        domain: "mozilla.org",
        date: "Sep 27",
        note: "Perceptually uniform color spaces and dark contrast tokens",
        tags: ["css", "design-tokens"],
      },
    ],
    mood_gallery: [
      {
        id: "mood-ds-1",
        url: "/assets/mood-sample-1.jpg",
        caption: "Sovereign Design Language System",
        tags: ["design", "cyber", "obsidian"],
        created_at: "Sep 27",
      },
      {
        id: "mood-ds-2",
        url: "/assets/mood-sample-2.jpg",
        caption: "High-Contrast Emerald Glyphs",
        tags: ["emerald", "typography"],
        created_at: "Sep 27",
      },
    ],
  },
  {
    id: 5,
    created_at: "2026-09-25T10:00:00Z",
    title: "Analytics Event Taxonomy",
    body: "Standardize events and improve data quality across sovereign creator funnel pipelines.",
    tags: ["analytics", "data"],
    kind: "milestone",
    status: "backlog",
    funnel_stage: "revenue",
    remind_at: "2026-10-20",
    events: [
      {
        id: "ev-an-1",
        title: "Taxonomy Schema Defined",
        time: "2d ago",
        author: "Product Architect",
        desc: "Drafted type-safe JSON schema for creator funnel events.",
        tags: ["schema", "events"],
      },
    ],
    bookmarks: [],
    mood_gallery: [],
  },
];


